# Lab-only ExternalSecret for fake provider testing.
# Pair with manifests/lab/dev-secretstore-fake.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-pull-secret
  namespace: dev
  labels:
    app.kubernetes.io/managed-by: external-secrets
    project: secrets-management-multi-cloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: dev-secretstore
    kind: SecretStore
  target:
    name: registry-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .host }}": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  dataFrom:
    - extract:
        key: dev/registry/pull-secret
        version: v1
