apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nodejs-zero-downtime
  namespace: zero-downtime-demo
  labels:
    app: nodejs-zero-downtime
    project: zero-downtime-deployments
    canary-stage: "10-percent"
  annotations:
    description: "Stage 1 canary — 10% green, 90% blue"
    haproxy.router.openshift.io/balance: roundrobin
    haproxy.router.openshift.io/disable_cookies: "true"
    haproxy.router.openshift.io/timeout: 30s
spec:
  host: ""
  to:
    kind: Service
    name: nodejs-blue
    weight: 90
  alternateBackends:
    - kind: Service
      name: nodejs-green
      weight: 10
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
