apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod-workload-sa
  namespace: prod
  labels:
    app.kubernetes.io/managed-by: external-secrets
    project: secrets-management-multi-cloud
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: prod
  labels:
    app.kubernetes.io/managed-by: external-secrets
    project: secrets-management-multi-cloud
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
    resourceNames: ["registry-pull-secret"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-secret-reader
  namespace: prod
  labels:
    app.kubernetes.io/managed-by: external-secrets
    project: secrets-management-multi-cloud
subjects:
  - kind: ServiceAccount
    name: prod-workload-sa
    namespace: prod
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
