apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    app.kubernetes.io/managed-by: external-secrets
    environment: dev
    project: secrets-management-multi-cloud
    secrets-tier: non-production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-secrets-quota
  namespace: dev
  labels:
    app.kubernetes.io/managed-by: external-secrets
    project: secrets-management-multi-cloud
spec:
  hard:
    secrets: "10"
    pods: "30"
    services: "10"
