apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    app.kubernetes.io/managed-by: external-secrets
    environment: prod
    project: secrets-management-multi-cloud
    secrets-tier: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-secrets-quota
  namespace: prod
  labels:
    app.kubernetes.io/managed-by: external-secrets
    project: secrets-management-multi-cloud
spec:
  hard:
    secrets: "10"
    pods: "50"
    services: "20"
