apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: dev-secretstore
  namespace: dev
  labels:
    app.kubernetes.io/managed-by: external-secrets
    project: secrets-management-multi-cloud
    provider: vault
spec:
  provider:
    vault:
      server: "https://vault.internal:8200"
      # AUTHOR TO VALIDATE — replace with your Vault server URL
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "dev-secret-reader"
          # AUTHOR TO VALIDATE — replace with your Vault Kubernetes auth role
          serviceAccountRef:
            name: dev-workload-sa
