apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: dev-secretstore
  namespace: dev
  labels:
    app.kubernetes.io/managed-by: external-secrets
    project: secrets-management-multi-cloud
    provider: aws
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      # AUTHOR TO VALIDATE — set your AWS region
      auth:
        jwt:
          serviceAccountRef:
            name: dev-workload-sa
            # Annotate dev-workload-sa with eks.amazonaws.com/role-arn
            # AUTHOR TO VALIDATE — replace account ID and IAM role name
