apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: dev-secretstore
  namespace: dev
  labels:
    app.kubernetes.io/managed-by: external-secrets
    project: secrets-management-multi-cloud
    provider: azure
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://YOUR-KEYVAULT-NAME.vault.azure.net"
      # AUTHOR TO VALIDATE — replace with your Key Vault URL
      serviceAccountRef:
        name: dev-workload-sa
        # Annotate dev-workload-sa with azure.workload.identity/client-id
        # AUTHOR TO VALIDATE — replace with your managed identity client ID
